# Generated by Django 2.2 on 2020-07-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0003_auto_20200715_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
