# Generated by Django 2.2 on 2020-08-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_post_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
