# Generated by Django 2.2 on 2020-07-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200716_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='poster',
        ),
    ]
