# Generated by Django 2.2 on 2020-07-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200716_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='author',
        ),
    ]
