# Generated by Django 2.2 on 2020-07-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0005_auto_20200716_1300'),
        ('dashboard', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='log_reg_app.User'),
        ),
    ]
